### ISSUE TITLE
Allow extended properties

### ISSUE THREAD

**Issue by jameskolce** [jameskolce/postcss-vertical-rhythm#5]
Currently it only looks for the `font` rule, it should also accept the extended syntax:

```CSS
:root {
    font-family: ...;
    font-size: ...;
    line-height: ...;
}
```
