### ISSUE TITLE
Omit font declarations inside print media query

### ISSUE THREAD

**Issue by jameskolce** [jameskolce/postcss-vertical-rhythm#6]
The following example makes it fail, for two reasons:

- [ ] The second font declaration uses a pt unit and it isn't present in the regex in https://github.com/jameskolce/postcss-vertical-rhythm/blob/master/index.js#L42
- [ ] Fixing the previous point, it ends up using the font values from the print media query.

```CSS
:root {
  font: 16px/1.5 "Helvetica", "Arial", sans-serif;
}

@media print {
  :root {
    font: 11pt / 1.3 "Georgia", "Times New Roman", "Times", serif;
  }
}

p {
  margin-bottom: 1vr;
  padding-top: .5vr;
}
```
